language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_06f6a8cb1961_key -iv $encrypted_06f6a8cb1961_iv -in vps.enc -out vps -d
  - chmod 600 vps
  - eval $(ssh-agent -s)
  - ssh-add vps
  - pip install -r requirements.txt

script: "./deploy.sh"
