language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_06f6a8cb1961_key -iv $encrypted_06f6a8cb1961_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - pip install -r requirements.txt
script: "./deploy.sh"
