site_name: DevOps documentation
extra_css:
  - css/syntax.css
theme:
  name: material
  custom_dir: 'theme'
  palette:
    primary: 'indigo'
    accent: 'pink'
  logo:
    icon: code
  feature:
    tabs: true
repo_name: 'victorboissiere/docs'
repo_url: 'https://github.com/victorboissiere/docs'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/victorboissiere'
    - type: 'twitter'
      link: 'https://twitter.com/victorboissiere'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/victorboissiere'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCgHlbMrsG2iBAguUQWbmD9Q'
copyright: 'Copyright &copy; 2018 Victor Boissiere'
markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - codehilite:
      guess_lang: false
      use_pygments: true
  - admonition
  - meta
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
